name: Unit tests

on: ["push", "pull_request"]

jobs:
  test-go:
    name: Run Go lint and unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: Install dependencies
        run: go get -t -v ./...
      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Vet
        run: go vet ./...
      - name: Run Go unit tests
        run: go test -v -race ./...